pipeline {
    agent any

    environment {
        // AWS credentials injected from Jenkins credentials store
        AWS_ACCESS_KEY_ID     = credentials('TP_FE_AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('TP_FE_AWS_SECRET_KEY')

        // Terraform variables as environment variables
        TF_VAR_region                = credentials('TP_FE_AWS_REGION_DEV')
        TF_VAR_cloudfront_acm_region = credentials('TP_FE_AWS_CLOUDFRONT_ACM_REGION')
        TF_VAR_domain_name           = credentials('TP_FE_AWS_DOMAIN_NAME_DEV')
        TF_VAR_hosted_zone_id        = credentials('TP_FE_AWS_HOSTED_ZONE_ID')
        TF_VAR_bucket_name           = credentials('TP_FE_AWS_S3_BUCKET_DEV')
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/ttrungn/ticket-prime-user-fe.git', branch: 'main'
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'cd terraform'
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh 'terraform plan'
            }
        }

        stage('Terraform Apply') {
            steps {
                input message: 'Approve Terraform Apply?', ok: 'Apply'
                sh 'terraform apply -auto-approve'
            }
        }

        stage('Build Application') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }

        stage('Deploy to S3') {
            steps {
                sh 'aws s3 sync ./build/ s3://$TF_VAR_bucket_name/ --delete'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}

